---
# Config parameters of task proposer
reuse_task_statistics: false
rand_selection_prob: 0.2
zone_center: 0.3
ucb_weight: 100 # high value like 100 ignores dist_to_zone
which_vlm: "human" # choices: "cogvlm", "gpt4v", "none", "human"
